name: Check & deploy API documentation
on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main
jobs:
  deploy-doc:
    if: ${{ github.event_name == 'push' }}
    name: Deploy API documentation on Bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bump-sh/github-action@v1
        with:
          doc: greenly
          token: ${{secrets.BUMP_TOKEN}}
          file: doc/api/rest_api.yaml
  api-diff:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check API diff on Bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bump-sh/github-action@v1
        with:
          doc: greenly
          token: ${{secrets.BUMP_TOKEN}}
          file: doc/api/rest_api.yaml
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}